[#function getDomain]
    [#assign domain = "https://b-fy.com"]
    [#assign site=sitefn.site()]
    [#assign domains=site.domains]
    [#if domains?hasContent && (domains?size > 0)]
      [#assign domain = domains[0]]
    [/#if]
    [#return domain]
[/#function]

[#function getStories folder limit=999 _sortBy=""]
    [#-- Assign default value of param sortBy as Freemarker doesn't handle null string values well. --]
    [#assign sortBy=(_sortBy?hasContent)?then(_sortBy, "desc")]

    [#assign stories = []]
    [#if sortBy=="desc"]
        [#assign query = "SELECT * FROM [mgnl:composition] AS s WHERE ISDESCENDANTNODE('" + folder + "') ORDER BY s.[created] DESC"]
        [#assign __stories = cmsfn.search("stories", query, "JCR-SQL2", "mgnl:composition")!]
    [#else]
        [#assign storiesFolder = cmsfn.nodeByPath(folder, "stories")!]
        [#assign __stories = (storiesFolder?hasContent)?then(cmsfn.children(storiesFolder, "mgnl:composition"), [])]
    [/#if]
    
    [#list __stories as __story]
        [#if __story?counter > limit?number]
            [#break]
        [/#if]
        [#assign stories = stories + [cmsfn.asContentMap(__story)]]
    [/#list]
    [#return stories]
[/#function]

[#function getStoryByName storyName]
    [#assign query = "SELECT * FROM [mgnl:composition] AS s WHERE name(s)='${storyName}'"]
    [#assign stories = cmsfn.search("stories", query, "JCR-SQL2", "mgnl:composition")!]
    [#if stories?hasContent]
        [#assign story = cmsfn.asContentMap(cmsfn.wrapForI18n(stories[0]))]
    [/#if]

    [#return story]
[/#function]

[#function getStoryByPath storyPath]
    [#return cmsfn.contentByPath(content.story, "stories")]
[/#function]

[#function getDefaultStory]
    [#assign folder = cmsfn.contentByPath('/blog', 'stories')!]
    [#assign stories = cmsfn.children(folder, "mgnl:composition")]
    [#if stories?hasContent]
        [#assign story = stories[0]]
    [/#if]

    [#return story]
[/#function]

[#function getTeamMember teamMemberId]
    [#return cmsfn.contentById(teamMemberId, "bfy-team")]
[/#function]

[#function getLinkByPagePath path]
    [#assign page = cmsfn.contentByPath(path)!]
    [#return page?hasContent?then(cmsfn.link(page), path)]
[/#function]
